{ config, pkgs, ... }:
{

  environment.shellAliases = {
    # Dumps logs to screen, then drops you into the RCON console indistinguishable from normal attaching sessions
    bnuy = "sudo docker logs minecraft-survival && sudo docker exec -it minecraft-survival rcon-cli";
    bnuy-lab = "sudo docker logs minecraft-lab && sudo docker exec -it minecraft-lab rcon-cli";
  };

  # Docker network so that all the Minecraft docker containers can talk to each other over IPV4
  systemd.services.init-minecraft-network = {
    description = "Create Docker network for Minecraft";
    after = [ "docker.service" ];
    requires = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig.Type = "oneshot";
    script = ''
      ${pkgs.docker}/bin/docker network inspect mc-net >/dev/null 2>&1 || ${pkgs.docker}/bin/docker network create mc-net
    '';
  };
  virtualisation.oci-containers = {
    backend = "docker";
    containers.velocity = {
      image = "itzg/mc-proxy";
      ports = [
        "25577:25577"
      ]; # Only Velocity is exposed to the world
      #environmentFiles = [ config.sops.secrets."minecraft_env".path ];
      extraOptions = [ "--network=mc-net" ];
      environment = {
        TYPE = "VELOCITY";
        #ONLINE_MODE = "true";
        COPY_PLUGINS_SRC = "/staging-plugins";
        # Plugins SPIGOT auto download , but not all plugins support it)
        PLUGINS = " 
          https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity
          https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity";
      };

      volumes = [
        "/var/lib/minecraft/velocity:/server"
        "/var/lib/minecraft/plugins/velocity:/staging-plugins:ro"
        "/etc/nixos/modules/development/minecraft-server/velocity.toml:/server/velocity.toml"
        "/var/lib/minecraft/velocity/forwarding.secret:/server/forwarding.secret"
      ];
    };
    #Generated by setupmc.com on 2026-03-24T23:23:07.298Z

    containers.minecraft-survival = {
      image = "itzg/minecraft-server";
      # getting secrets to work is a bitch
      environmentFiles = [
        config.sops.secrets."minecraft_env".path
      ];

      # Attach to local docker network
      extraOptions = [
        "--network=mc-net" # internal connections
        "--cpus=6"
        "--cpuset-cpus=0-5"
      ]; # Server Properties

      environment = {
        EULA = "true";
        TYPE = "PAPER";
        VERSION = "1.21.11";
        #SERVER_IP = ""; # Bind to all interfaces inside the container
        INIT_MEMORY = "8G";
        MAX_MEMORY = "8G";
        MAX_PLAYERS = "20";
        DIFFICULTY = "hard";
        MODE = "survival";
        TZ = "America/New_York";

        ICON = "data/server-icon.png";

        ONLINE_MODE = "false";
        ENFORCE_SECURE_PROFILE = "false"; # Required for Floodgate also fuck MICROSOFT

        ENABLE_AUTOPAUSE = "true";
        MAX_TICK_TIME = "-1";
        # How long to wait after the last player leaves before pausing
        AUTOPAUSE_TIMEOUT_EST = "172800"; # 2 days in seconds
        # server list message motd while sleeping
        AUTOPAUSE_KICK_MESSAGE = "Bnuyhole is sleeping. Please wait 60s for wake-up!";
        # prevents the server from pausing if there is a backup running
        AUTOPAUSE_RESERVED_ADR = "mc-backup";

        # Plugins SPIGOT auto download , but not all plugins support it)
        COPY_PLUGINS_SRC = "/staging-plugins";
        SPIGET_RESOURCES = ""; # Spigot ID's
        # Plugins auto-download
        PLUGINS = "
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot";

        # RCON Setup
        # Internal only DO NOT expose in ports
        ENABLE_RCON = "true";
        JVM_OPTS = "--add-modules=jdk.incubator.vector -XX:+UseZGC -XX:+ZGenerational -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+UseNUMA -XX:+PerfDisableSharedMem -XX:ZUncommitDelay=60";
      };
      volumes = [
        "/var/lib/minecraft/survival:/data"
        "/run/secrets/minecraft:/run/secrets/minecraft:ro"
        "/var/lib/minecraft/plugins/survival:/staging-plugins:ro"
      ];
    };
    containers.minecraft-lab = {
      image = "itzg/minecraft-server";
      # NO PORTS EXPOSED.
      environmentFiles = [ config.sops.secrets."minecraft_env".path ];
      extraOptions = [
        "--network=mc-net"
      ];
      environment = {
        EULA = "true";
        TYPE = "PAPER";
        VERSION = "1.21.11"; # wait this is cool
        INIT_MEMORY = "3G";
        MAX_MEMORY = "3G";
        MODE = "adventure";
        JVM_OPTS = "--add-modules=jdk.incubator.vector -XX:+UseZGC -XX:+ZGenerational -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+UseNUMA -XX:+PerfDisableSharedMem -XX:ZUncommitDelay=60";

        ONLINE_MODE = "false";

        # Plugins SPIGOT auto download , but not all plugins support it)
        COPY_PLUGINS_SRC = "/staging-plugins";
        PLUGINS = "
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot";
        REMOVE_OLD_MODS = "true";
        REMOVE_OLD_MODS_DEPTH = "1";

        # Autopause
        ENABLE_AUTOPAUSE = "true";
        MAX_TICK_TIME = "-1";
        AUTOPAUSE_TIMEOUT_EST = "7200"; # 2 hours in seconds
        AUTOPAUSE_TIMEOUT_INIT = "7200";

        # server list message motd while sleeping
        AUTOPAUSE_KICK_MESSAGE = "Bnuyhole-lab is sleeping. Please wait 60s for wake-up!";
        # prevents the server from pausing if there is a backup running
        AUTOPAUSE_RESERVED_ADR = "mc-backup";

        ENABLE_RCON = "true";
      };
      volumes = [
        "/var/lib/minecraft/lab:/data"
        "/run/secrets/minecraft:/run/secrets/minecraft:ro"
        "/var/lib/minecraft/plugins/lab:/staging-plugins:ro"
      ];
    };

    containers.mc-backup = {
      image = "itzg/mc-backup";
      # Local network for docker containers
      extraOptions = [
        "--network=mc-net"
        "--cpu-shares=256" # Cpu priority setting to 1/4th the rest of the system
      ]; # by setting the cpu priority lower, its less likely to lag, and its not time sensitive or too important so it can be lowered thusly

      environmentFiles = [
        config.sops.secrets."minecraft_env".path
      ];

      environment = {
        BACKUP_METHOD = "restic";
        RESTIC_REPOSITORY = "/backups";
        RESTIC_HOSTNAME = "Bnuyhole-Network";

        # Backup logic
        BACKUP_INTERVAL = "30m";
        PRUNE_RESTIC_RETENTION = "--keep-last 5 --keep-hourly 24 --keep-daily 12 --keep-weekly 4 --keep-monthly 3  --keep-yearly 2";
        PAUSE_IF_NO_PLAYERS = "false";

        # Terrible evil vile server player count checker that needs to be merged with itzg
        PRE_BACKUP_SCRIPT = ''
          echo "Checking network player count..."

          # 1. Capture raw output
          RAW_SURVIVAL=$(rcon-cli --host minecraft-survival list 2>/dev/null || echo "offline")
          RAW_LAB=$(rcon-cli --host minecraft-lab list 2>/dev/null || echo "offline")

          # 2. Strip ANSI Color Codes
          # This sed command finds the ESC character and removes everything between '[' and 'm'
          CLEAN_SURVIVAL=$(echo "$RAW_SURVIVAL" | sed "s/$(printf '\033')\[[0-9;]*m//g")
          CLEAN_LAB=$(echo "$RAW_LAB" | sed "s/$(printf '\033')\[[0-9;]*m//g")

          # 3. Extract the actual player count
          # Now that the '31m' and '33m' are gone, we can safely grab the first number after "There are"
          P_SURVIVAL=$(echo "$CLEAN_SURVIVAL" | sed -nE 's/.*There are[^0-9]*([0-9]+).*/\1/p' | head -n 1)
          P_LAB=$(echo "$CLEAN_LAB" | sed -nE 's/.*There are[^0-9]*([0-9]+).*/\1/p' | head -n 1)

          # 4. Fallbacks
          P_SURVIVAL=''${P_SURVIVAL:-0}
          P_LAB=''${P_LAB:-0}
          TOTAL_PLAYERS=$((P_SURVIVAL + P_LAB))

          echo "Survival: $P_SURVIVAL players | Lab: $P_LAB players"
          echo "Total Network: $TOTAL_PLAYERS"

          if [ "$TOTAL_PLAYERS" -eq 0 ]; then
            echo "Zero players detected. Aborting backup."
            exit 1
          fi

          echo "Players found! Continuing backup..."
        '';
        # RCON local terminal for sending commands and fetching data locally
        RCON_HOST = "minecraft-survival";
        #RCON_PASSWORD = "9xD7£2D/AWG+^2q";
      };
      volumes = [
        "/var/lib/minecraft:/data:ro" # Read-only so backups can't break the world
        "/var/backups/minecraft:/backups"
      ];
      dependsOn = [
        "minecraft-survival"
        "minecraft-lab"
      ];
    };

  };

  /*
    systemd.services.remote-mc-backup = {
      description = "Rsync Minecraft Backups to Remote Storage";
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${pkgs.rsync}/bin/rsync -avz --delete /var/backups/minecraft/ user@ip:/backups/minecraft/";
      };
    };

    systemd.timers.remote-mc-backup = {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = "03:00:00"; # Run daily at 3am
        Persistent = true;
      };
    };
  */

  systemd.services.minecraft-secret-sanitizer = {
    description = "Clean Paper YAML duplicates and CRLF";
    before = [ "docker-minecraft-survival.service" ];
    after = [ "sops-nix.service" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      User = "root";
      # We wrap the script in ${ } to turn the derivation into a string path for ExecStart
      ExecStart = "${pkgs.writeShellScript "minecraft-sanitizer" ''
        # Set PATH so we don't have to use full paths for every command
        PATH="${pkgs.gnused}/bin:${pkgs.coreutils}/bin"
        FILE="/var/lib/minecraft/survival/config/paper-global.yml"

        if [ -f "$FILE" ]; then
          echo "Sanitizing $FILE..."
          # Use \x27 instead of to avoid Nix syntax errors.
          # This removes the exact line: secret: 
          sed -i "/secret: \x27\x27/d" "$FILE"
          # This removes any lines that end with 'secret: ' (and trailing whitespace)
          sed -i "/secret:[[:space:]]*$/d" "$FILE"
          # This removes Windows line endings (CRLF -> LF)
          sed -i "s/\r//g" "$FILE"
          echo "Sanitization complete."
        else
          echo "Warning: $FILE not found."
        fi
      ''}";
      RemainAfterExit = true;
    };
  };

  systemd.services.mc-watchdog = {
    description = "Minecraft Server Watchdog";
    path = [
      pkgs.docker
      pkgs.util-linux
      #pkgs.libnotify # removed because it runs as root user, and thats in no way usefull
    ]; # docker wall and notify-send, respectfully
    script = ''
      # Check if the server responds to a ping using mc-monitor
      if ! docker exec minecraft-survival mc-monitor status --host localhost --port 25565 >/dev/null 2>&1; then
        echo "WATCHDOG: Minecraft-survival server is unreachable"
        # echo to all SSH terminals
        sudo wall "CRITICAL: Watchdog: Minecraft-survival server is down or unresponsive"
        #notify-send -u critical "CRITICAL: Watchdog: Minecraft-survival server is down or unresponsive"
      fi
      if ! docker exec minecraft-lab mc-monitor status --host localhost --port 25565 >/dev/null 2>&1; then
        echo "WATCHDOG: Minecraft-lab server is unreachable"
        # echo to all SSH terminals
        sudo wall "CRITICAL: Watchdog: Minecraft-lab server is down or unresponsive"
        #notify-send -u critical "CRITICAL: Watchdog: Minecraft-lab server is down or unresponsive"
      fi
    '';
    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };

  # Watchdog timer that activates minecraft watchdog (above)
  systemd.timers.mc-watchdog = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "3m"; # Give the server 3 mins to start up before yelling
      OnUnitActiveSec = "1m"; # Run every 1 minute
    };
  };
  systemd.services."docker-minecraft-survival" = {
    preStart = ''

      mkdir -p /var/lib/minecraft/survival/config

      cp -f ${./paper-global.yml} /var/lib/minecraft/survival/config/paper-global.yml

      # Drop the bunny image into the root of the server data folder
      cp -f /etc/nixos/assets/server-icon.png /var/lib/minecraft/survival/server-icon.png


      mkdir -p /var/lib/minecraft/survival
      chown -R 1000:1000 /var/lib/minecraft/survival
      chmod -R u+rwX /var/lib/minecraft/survival
    '';
  };
  systemd.services."docker-minecraft-lab" = {
    preStart = ''
      mkdir -p /var/lib/minecraft/lab
      chown -R 1000:1000 /var/lib/minecraft/lab
      chmod -R u+rwX /var/lib/minecraft/lab
    '';
  };

  environment.systemPackages = with pkgs; [
    # This creates a sh in /run/current-system/sw/bin/bnuy-check
    (writeShellScriptBin "bnuy-check" ''
      case "$1" in
        snapshots) sudo docker exec mc-backup restic snapshots ;;
        check)     sudo docker exec mc-backup restic check ;;
        verify)    sudo docker exec mc-backup restic check --read-data ;;
        unlock)    sudo docker exec mc-backup restic unlock ;;
        ls)        sudo docker exec mc-backup restic ls "''${2:-latest}" ;;
        
        stats)
          echo "Scanning Bnuyhole Repository..."
          
          JSON_SNAPS=$(sudo docker exec mc-backup restic snapshots --json)
          COUNT=$(echo "$JSON_SNAPS" | ${pkgs.jq}/bin/jq length)
          OLDEST=$(echo "$JSON_SNAPS" | ${pkgs.jq}/bin/jq -r '.[0].time[:16]' | tr 'T' ' ')
          NEWEST=$(echo "$JSON_SNAPS" | ${pkgs.jq}/bin/jq -r '.[-1].time[:16]' | tr 'T' ' ')

          LATEST_JSON=$(sudo docker exec mc-backup restic ls latest --json)
          SURVIVAL_SIZE=$(echo "$LATEST_JSON" | ${pkgs.jq}/bin/jq -r 'select(.type=="file" and .path != null and (.path | contains("/survival/"))) | .size' | awk '{s+=$1} END {print s+0}')
          LAB_SIZE=$(echo "$LATEST_JSON" | ${pkgs.jq}/bin/jq -r 'select(.type=="file" and .path != null and (.path | contains("/lab/"))) | .size' | awk '{s+=$1} END {print s+0}')

          RESTORE_SIZE=$(sudo docker exec mc-backup restic stats --mode restore-size --json | ${pkgs.jq}/bin/jq .total_size)
          RAW_SIZE=$(sudo docker exec mc-backup restic stats --mode raw-data --json | ${pkgs.jq}/bin/jq .total_size)
          SAVED=$((RESTORE_SIZE - RAW_SIZE))
          PERCENT_REDUCED=$(awk "BEGIN { printf \"%.2f\", (($RESTORE_SIZE - $RAW_SIZE) / $RESTORE_SIZE) * 100 }")
          RATIO=$(awk "BEGIN { if ($RAW_SIZE > 0) printf \"%.2f\", $RESTORE_SIZE / $RAW_SIZE; else print \"0.00\" }")

          to_gib() { echo | awk "{ printf \"%.2f GiB\", $1 / 1024 / 1024 / 1024 }"; }

          echo ""
          echo "========================================="
          echo "      BNUYHOLE NETWORK BACKUP STATS      "
          echo "========================================="
          echo " Snapshots          : $COUNT"
          echo " Range              : $OLDEST  ->  $NEWEST"
          echo "-----------------------------------------"
          echo " Survival Footprint : $(to_gib $SURVIVAL_SIZE)"
          echo " Lab Footprint      : $(to_gib $LAB_SIZE)"
          echo "-----------------------------------------"
          echo " Uncompressed Size  : $(to_gib $RESTORE_SIZE)"
          echo " Actual Size        : $(to_gib $RAW_SIZE)"
          echo " "
          echo " Compression Saved  : $(to_gib $SAVED) !"
          echo " Percentage smaller : $PERCENT_REDUCED%"
          echo " Compression ratio  : ''${RATIO}:1"
          echo "========================================="
          ;;
        *)
          echo "Usage: bnuy-check {snapshots|stats|ls|check|verify|unlock}"
          ;;
      esac
    '')

    #debating calling this rabbit-recover
    (writeShellScriptBin "bnuy-rollback" ''
      if [ "$EUID" -ne 0 ]; then echo "ERROR: Please run with sudo."; exit 1; fi

      # If somone cancels the rolback mid rolback, some nasty stuff used to happen, so i added this edge case.
      # im sure this is only a bandaid, but it works well in my shallow testing so ¯\_(ツ)_/¯      
      cleanup() {
        echo ""
        echo "Exiting... ensuring backup service is online." &
        systemctl start "docker-mc-backup"
        exit 1
      }

      trap cleanup SIGINT SIGTERM

      RESTIC_PASSWORD=$(grep '^RESTIC_PASSWORD=' "${
        config.sops.secrets."minecraft_env".path
      }" | cut -d '=' -f 2-)
      ACTION=$1

      perform_restore() {
        local SNAP_ID=$1
        local ACTION_NAME=$2
        local TARGET=$3

        local STATE_DIR="/var/lib/minecraft/.rollback/$TARGET"
        mkdir -p "$STATE_DIR"

        echo "Disabling backup service to prevent race conditions..."
        systemctl stop docker-mc-backup

        countdown 60 "[''${TARGET^^}] $ACTION_NAME starting in:" "Stopping in:" "true" "$TARGET"
        
        if [ "$TARGET" == "all" ]; then
          for s in minecraft-survival minecraft-lab; do
            echo "Disabling $s.."
            sudo docker stop "$s"
          done
        else
          sudo docker stop $TARGET 
        fi

        if [ "$TARGET" == "all" ]; then
          for s in survival lab; do
            echo "Scrubbing $s live data to prevent Ghost Chunks..."
            rm -rf "/var/lib/minecraft/$s/world" "/var/lib/minecraft/$s/world_nether" "/var/lib/minecraft/$s/world_the_end"
          done
        else
          rm -rf "/var/lib/minecraft/$TARGET/world" "/var/lib/minecraft/$TARGET/world_nether" "/var/lib/minecraft/$TARGET/world_the_end"
        fi
        
        if [ "$TARGET" == "all" ]; then
          for s in survival lab; do
            echo "Restoring $s from snapshot: $SNAP_ID..."
            sudo docker run --rm \
              -v /var/lib/minecraft:/data \
              -v /var/backups/minecraft:/backups \
              -e RESTIC_PASSWORD="$RESTIC_PASSWORD" \
              restic/restic -r /backups restore "$SNAP_ID" --target / --include "/data/$s"         
          done
        else
          echo "Restoring $TARGET from snapshot: $SNAP_ID..."
          # We mount the root minecraft folder, and tell restic to only include the specific server's folder
          sudo docker run --rm \
            -v /var/lib/minecraft:/data \
            -v /var/backups/minecraft:/backups \
            -e RESTIC_PASSWORD="$RESTIC_PASSWORD" \
            restic/restic -r /backups restore "$SNAP_ID" --target / --include "/data/$TARGET"
        fi

        if [ "$TARGET" == "all" ]; then
          for s in survival lab; do
            echo "Restarting $s service..."

            systemctl reset-failed docker-mc-backup "docker-minecraft-$s"
            systemctl start "docker-minecraft-$s"
          done
        else
          systemctl reset-failed docker-mc-backup "docker-minecraft-$TARGET"
          systemctl start "docker-minecraft-$TARGET"
        fi

        systemctl start docker-mc-backup
        echo "$TARGET $ACTION_NAME Complete."

      }

      case "$ACTION" in
        list) sudo docker exec mc-backup restic snapshots ;; # I get this is a duplicate, sue me, its important functionality
        this)
          SNAP_ID=$2
          SERVER="''${3:-lab}"
          if [ -z "$SNAP_ID" ]; then echo "Provide Snapshot ID"; exit 1; fi
          
          STATE_DIR="/var/lib/minecraft/.rollback/$SERVER"
          mkdir -p "$STATE_DIR"
          
          echo "Creating pre-rollback safety snapshot for $SERVER..."
          sudo docker exec mc-backup backup now
          
          SAFETY_ID=$(sudo docker exec mc-backup restic snapshots --latest 1 --json | ${pkgs.jq}/bin/jq -r '.[0].short_id')
          echo "$SAFETY_ID" > "$STATE_DIR/last-safety-id"

          perform_restore "$SNAP_ID" "rollback" "$SERVER"
          ;;
        undo)
          SERVER="''${2:-lab}"
          STATE_DIR="/var/lib/minecraft/.rollback/$SERVER"
          if [ ! -f "$STATE_DIR/last-safety-id" ]; then echo "No undo history for $SERVER."; exit 1; fi
          RESTORE_SAFETY_ID="$(cat "$STATE_DIR/last-safety-id")"
          
          echo "Creating a pre-rollback last-safety-id so you can use  this command again, and it will functionally 'redo'"

          NEW_SAFETY_ID=$(sudo docker exec mc-backup restic snapshots --latest 1 --json | ${pkgs.jq}/bin/jq -r '.[0].short_id')
          echo "$NEW_SAFETY_ID" > "$STATE_DIR/last-safety-id"
          
          echo "restoring to the last rollback at the snapshot : $RESTORE_SAFETY_ID"
                    

          perform_restore "$RESTORE_SAFETY_ID" "rollback" "$SERVER"
          ;;
        *)
          echo "=== Bnuy-Rollback Help ==="
          echo "Usage: bnuy-rollback {list|this [snapshot_id] OR [server]|undo [server]}"
          echo ""
          echo "Parameters:"
          echo "  snapshot_id : Obtain via 'bnuy-rollback list'"
          echo "  server      : survival or lab (default: lab)"
          echo ""
          echo "Examples:"
          echo "  sudo bnuy-rollback list survival"
          echo "  sudo bnuy-rollback this 2a931bbd survival"
          echo "  sudo bnuy-rollback undo lab"
          ;;
      esac
    '')
    (writeShellScriptBin "countdown" ''
      #!/usr/bin/env bash
      if [ "$EUID" -ne 0 ]; then echo "ERROR: Run with sudo."; exit 1; fi

      total="''${1:-60}"

      InformServer="''${5:-all}"
      Statement="''${2:-Scheduled Server restart is in}"
      Countdown="''${3:-Restarting in}"

      # Command to run after the previous yelling 
      Command="''${4:-sudo systemctl restart docker-minecraft-survival.service}"

      # Gotta make sure its a actual command first
      FIRST_WORD=$(echo "$Command" | awk '{print $1}')
      if ! command -v "$FIRST_WORD" >/dev/null 2>&1; then echo "ERROR: Invalid command."; exit 1; fi
      echo "Countdown started for $total seconds..."

      # A smart way to only inform the servers that need to know of the rollback, potentially stemming fear if all servers heard a rollback was starting
      broadcast() {
        local msg="$1"
        if [ "$InformServer" == "all" ]; then
          for s in minecraft-survival minecraft-lab; do
            sudo docker exec "$s" rcon-cli say "$msg" >/dev/null 2>&1 || true
          done
        else
          sudo docker exec "minecraft-$InformServer" rcon-cli say "$msg" >/dev/null 2>&1 || true
        fi
      }

      for ((t = total; t > 0; t--)); do
        if ((t % 3600 == 0 && t != 0)); then
          string="''${Statement} $((t / 3600)) Hours(s)"
          broadcast "''${string}"
          echo "$string"
        elif ((t % 300 == 0 && t != 0)); then
          string="''${Statement} $((t / 60)) Minutes(s)"
          broadcast "''${string}"
          echo "$string"
        elif ((t == 60)); then
          string="''${Statement} $((t / 60)) Minutes(s)"
          broadcast "''${string}"
          echo "$string"
        elif ((t == 30)); then
          string="''${Statement} $t SECONDS"
          broadcast "''${string}"
          echo "$string"
        elif ((t == 15)); then
          string="''${Statement} $t SECONDS"
          broadcast "''${string}"
          echo "$string"
        elif ((t <= 10)); then
          string="''${Statement} $t"
          broadcast "''${string}"
          echo "$string"
        fi

        sleep 1
      done
      echo "executing the command '$4'"
      eval "$4"
    '')
  ];
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 25577 ]; # Velocity Java
    allowedUDPPorts = [ 19132 ]; # Geyser Bedrock
  };
}
