# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e54583d6-c352-469a-8ebe-367dab13727d";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-e54583d6-c352-469a-8ebe-367dab13727d".device = "/dev/disk/by-uuid/e54583d6-c352-469a-8ebe-367dab13727d";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-e54583d6-c352-469a-8ebe-367dab13727d";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-e54583d6-c352-469a-8ebe-367dab13727d";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2179-64F2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  boot.initrd.luks.devices."luks-d6569e19-e6ed-4336-90b6-8be1b871fdce".device = "/dev/disk/by-uuid/d6569e19-e6ed-4336-90b6-8be1b871fdce";

  swapDevices =
    [ { device = "/dev/mapper/luks-d6569e19-e6ed-4336-90b6-8be1b871fdce"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
