# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7eb42619-ccc0-4ef3-b3fc-438291f7f188";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-7eb42619-ccc0-4ef3-b3fc-438291f7f188".device = "/dev/disk/by-uuid/7eb42619-ccc0-4ef3-b3fc-438291f7f188";

  boot.initrd.luks.devices."luks-fcad4af5-04b8-40b8-8f30-5d6f7177c881".device = "/dev/disk/by-uuid/fcad4af5-04b8-40b8-8f30-5d6f7177c881";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-7eb42619-ccc0-4ef3-b3fc-438291f7f188";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-7eb42619-ccc0-4ef3-b3fc-438291f7f188";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5458-79D2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fcad4af5-04b8-40b8-8f30-5d6f7177c881"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
