# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-uuid/FAKE-NEBULA-ROOT";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/home" = lib.mkDefault {
    device = "/dev/disk/by-uuid/FAKE-NEBULA-ROOT";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/nix" = lib.mkDefault {
    device = "/dev/disk/by-uuid/FAKE-NEBULA-ROOT";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-uuid/FAKE-NEBULA-BOOT";
    fsType = "vfat";
  };

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
