{ config, lib, pkgs, vars, ... }:

let
  # Thin wrapper around nixpkgs' `services.step-ca` module so the LAN CA can be
  # enabled declaratively via `vars.serverModules.step-ca`.
  #
  # CA state lives in /var/lib/step-ca (StateDirectory of the `step-ca` systemd
  # service, run as a DynamicUser - NOT root). Config comes from ./ca.json,
  # which was generated by `step ca init` (run manually once) and imported via
  # fromJSON; the `address`/`port` options below override settings.address.
  #
  # The intermediate key and the provisioner's encryptedKey are decrypted at
  # startup using the CA password, supplied via
  # services.step-ca.intermediatePasswordFile (a sops secret).
  cfg = config.services.step-ca;

  rootCa = ./root_ca.crt;
in
{
  config = lib.mkMerge [
    {
      # Trust the bnuy LAN root CA (via vars.trustBnuyCA) so browsers and
      # clients validate step-ca-issued leaf certs without warnings. Always
      # follows ./root_ca.crt, so a CA rotation is picked up on next rebuild.
      security.pki.certificateFiles = lib.mkIf vars.trustBnuyCA [ rootCa ];
    }
    (lib.mkIf cfg.enable {
      services.step-ca = {
        address = "127.0.0.1";
        port = 9000;
        settings = builtins.fromJSON (builtins.readFile ./ca.json);
        intermediatePasswordFile = config.sops.secrets."step-ca/password".path;
      };

      # Run as the static `step-ca` system user (declared by the module) instead
      # of a DynamicUser. DynamicUser relocates the state dir to /var/lib/private
      # (0700 root), which the service cannot traverse once the CA data exists;
      # a static user keeps /var/lib/step-ca directly accessible and non-root.
      systemd.services.step-ca.serviceConfig.DynamicUser = lib.mkForce false;

      # Tools for issuing/renewing leaf certs (e.g. for the pterodactyl node).
      environment.systemPackages = [
        pkgs.step-ca
        pkgs.step-cli
      ];

      sops.secrets."step-ca/password" = {
        sopsFile = ./secrets.yaml;
        mode = "0440";
      };

      # Restic repo password for step-ca-backup.
      sops.secrets."step-ca/backup_password" = {
        sopsFile = ./secrets.yaml;
        owner = "root";
        mode = "0400";
      };

      # -------------------------------------------------------------------
      # Backup: nightly restic into /var/backups/step-ca/repo. This is the
      # CA itself - root/intermediate keys, provisioner config, issued-cert
      # accounting db. Losing it invalidates every leaf cert on the LAN at
      # once. Tiny (~165K), so a plain staged copy; the sqlite db gets a
      # consistent .backup.
      # -------------------------------------------------------------------
      systemd.tmpfiles.rules = [
        "d /var/backups 0755 root root -"
        "d /var/backups/step-ca 0700 root root -"
        "d /var/cache/restic 0700 root root -"
      ];

      systemd.services.step-ca-backup = {
        description = "step-ca: restic backup (CA keys, config, cert db)";
        after = [ "step-ca.service" "sops-nix.service" ];
        wants = [ "sops-nix.service" ];
        path = [
          pkgs.restic
          pkgs.sqlite
          pkgs.coreutils
        ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          WorkingDirectory = "/var/backups/step-ca";
          ReadWritePaths = [ "/var/backups/step-ca" ];
          PrivateTmp = true;
          NoNewPrivileges = true;
          Nice = 10;
          # systemd gives oneshot units no $HOME/$XDG_CACHE_HOME; restic
          # refuses to run without a cache dir, so pin one.
          Environment = "RESTIC_CACHE_DIR=/var/cache/restic";
        };
        script = ''
          set -eu
          export RESTIC_PASSWORD=$(cat ${config.sops.secrets."step-ca/backup_password".path})
          # Bare `restic` has no default repo; point it at this module's repo.
          export RESTIC_REPOSITORY=/var/backups/step-ca/repo
          mkdir -p repo staging

          rm -rf staging/*
          src=/var/lib/step-ca
          for d in certs config secrets templates; do
            [ -d "$src/$d" ] && cp -r "$src/$d" staging/
          done
          if [ -f "$src/db/db.sqlite" ]; then
            mkdir -p staging/db
            sqlite3 "$src/db/db.sqlite" ".backup 'staging/db/db.sqlite'"
          fi

          if ! restic snapshots >/dev/null 2>&1; then
            restic init
          fi
          restic backup staging --tag step-ca
          restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune
        '';
      };

      systemd.timers.step-ca-backup = {
        description = "step-ca: nightly backup";
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnCalendar = "*-*-* 05:00:00";
          Persistent = true;
        };
      };
    })
  ];
}
