#!/usr/bin/env bash
set -euo pipefail

ISO_DIR="${ISO_DIR:-/srv/iso}"
OUTPUT="${OUTPUT:-/srv/tftp/iso-menu.ipxe}"
LISTEN_IP="${LISTEN_IP:-192.168.1.166}"
HTTPS_PORT="${HTTPS_PORT:-8443}"
PROTOCOL="${PROTOCOL:-https}"
TFTP_ROOT="${TFTP_ROOT:-/srv/tftp}"
ISO_FILES_DIR="${TFTP_ROOT}/iso-files"

# Ensure xorriso is installed
if ! command -v xorriso &>/dev/null; then
    echo "gen-menu.sh: ERROR: xorriso not found. Install with: nix-shell -p xorriso" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT")" "$ISO_FILES_DIR"
rm -f "$OUTPUT"

# Helper: extract a file from ISO
extract_from_iso() {
    local iso=$1 src=$2 dst=$3
    if [ ! -f "$dst" ] || [ "$iso" -nt "$dst" ]; then
        mkdir -p "$(dirname "$dst")"
        xorriso -indev "$iso" -osirrox on -extract "$src" "$dst" 2>/dev/null
    fi
}

# Helper: find files by glob in ISO
find_in_iso() {
    local iso=$1 pattern=$2
    xorriso -indev "$iso" -find / -name "$pattern" -type f 2>/dev/null | head -1
}

# Helper: determine if ISO is Windows
is_windows_iso() {
    local iso=$1
    xorriso -indev "$iso" -find / -name "bootmgr" 2>/dev/null | grep -q bootmgr && return 0
    xorriso -indev "$iso" -find /efi/microsoft 2>/dev/null | grep -q microsoft && return 0
    return 1
}

# Helper: find squashfs path in ISO
find_squashfs_in_iso() {
    local iso=$1
    local path
    path=$(find_in_iso "$iso" "nix-store.squashfs")
    [ -n "$path" ] && echo "$path" && return 0
    path=$(find_in_iso "$iso" "filesystem.squashfs")
    [ -n "$path" ] && echo "$path" && return 0
    path=$(find_in_iso "$iso" "squashfs.img")
    [ -n "$path" ] && echo "$path" && return 0
    path=$(find_in_iso "$iso" "*.squashfs")
    [ -n "$path" ] && echo "$path" && return 0
    return 1
}

# Helper: find kernel in ISO
find_kernel_in_iso() {
    local iso=$1
    local path
    path=$(find_in_iso "$iso" "vmlinuz*")
    [ -n "$path" ] && echo "$path" && return 0
    path=$(find_in_iso "$iso" "bzImage")
    [ -n "$path" ] && echo "$path" && return 0
    return 1
}

cat > "$OUTPUT" << PROLOGUE
#!ipxe
# Auto-generated by gen-menu.sh - run again after adding/removing ISOs

:start
set menu-timeout 0
cpair --foreground 11 1
cpair --foreground 15 2
cpair --foreground 5 3

menu Select ISO to Boot
item --gap    up/down Navigate - Enter Select - b = Back to Main Menu
item --gap -- -------------------------------------------------------
PROLOGUE

count=0
for iso in "$ISO_DIR"/*.iso; do
    [ -f "$iso" ] || continue
    name=$(basename "$iso" .iso)
    item_name="iso_${name//[^a-zA-Z0-9_]/_}"
    display="${name:0:68}"

    # Detect type
    type=""
    if is_windows_iso "$iso"; then
        type="windows"
    elif find_squashfs_in_iso "$iso" >/dev/null 2>&1; then
        type="linux"
    else
        type="unknown"
    fi

    label=""
    case "$type" in
        windows) label=" [Windows]" ;;
        linux)   label=" [Linux]" ;;
        unknown) label=" [?]" ;;
    esac

    if [ "$count" -lt 9 ]; then
        echo "item --key $((count + 1)) ${item_name}    [$((count + 1))] ${display}${label}" >> "$OUTPUT"
    else
        echo "item ${item_name}    ${display}${label}" >> "$OUTPUT"
    fi
    count=$((count + 1))
done

if [ "$count" -eq 0 ]; then
    echo "item --gap    (no ISOs found in ${ISO_DIR})" >> "$OUTPUT"
fi

cat >> "$OUTPUT" << EPILOGUE
item --gap -- --------------------------------
item --key b back     [b] <-- Back to Main Menu
choose selected || goto back
goto \${selected}

EPILOGUE

if [ "$count" -gt 0 ]; then
    for iso in "$ISO_DIR"/*.iso; do
        [ -f "$iso" ] || continue
        name=$(basename "$iso" .iso)
        item_name="iso_${name//[^a-zA-Z0-9_]/_}"
        safe_name="${name//[^a-zA-Z0-9_-]/_}"

        cat >> "$OUTPUT" << CENTRY
:${item_name}
echo Booting: ${name}
CENTRY

        if is_windows_iso "$iso"; then
            iso_url="${PROTOCOL}://${LISTEN_IP}:${HTTPS_PORT}/iso/$(basename "$iso" | sed 's/ /%20/g')"
            cat >> "$OUTPUT" << SANENTRY
sanboot "${iso_url}"
echo Boot failed
prompt Press ENTER to return to menu
goto start

SANENTRY
        else
            squashfs_path=$(find_squashfs_in_iso "$iso" || true)
            kernel_path=$(find_kernel_in_iso "$iso" || true)

            if [ -n "$squashfs_path" ] && [ -n "$kernel_path" ]; then
                echo "  Extracting: ${name} (kernel + squashfs)" >&2

                extract_from_iso "$iso" "$kernel_path" "${ISO_FILES_DIR}/${safe_name}/kernel"
                extract_from_iso "$iso" "$squashfs_path" "${ISO_FILES_DIR}/${safe_name}/root.squashfs"

                kernel_url="${PROTOCOL}://${LISTEN_IP}:${HTTPS_PORT}/iso-files/${safe_name}/kernel"
                squashfs_url="${PROTOCOL}://${LISTEN_IP}:${HTTPS_PORT}/iso-files/${safe_name}/root.squashfs"

                cat >> "$OUTPUT" << LINUXENTRY
kernel ${kernel_url} squashfs_url=${squashfs_url} console=tty0
initrd ${PROTOCOL}://${LISTEN_IP}:${HTTPS_PORT}/wrapper-initrd.gz
boot

LINUXENTRY
            else
                echo "  WARNING: ${name} - could not find kernel/squashfs, falling back to sanboot" >&2
                iso_url="${PROTOCOL}://${LISTEN_IP}:${HTTPS_PORT}/iso/$(basename "$iso" | sed 's/ /%20/g')"
                cat >> "$OUTPUT" << FALLBACK
sanboot "${iso_url}"
echo Boot failed
prompt Press ENTER to return to menu
goto start

FALLBACK
            fi
        fi
    done
fi

cat >> "$OUTPUT" << BACK
:back
exit
BACK

echo "gen-menu.sh: wrote ${count} ISO entr${count} to ${OUTPUT}"
