{ pkgs, ... }:

{
  # GTK theming applied at runtime by apply-app-themes.sh from the quickshell palette
  gtk = {
    enable = true;
    theme = {
      # adw-gtk3 gives GTK3 apps (GNOME MultiWriter, etc.) a dark theme engine;
      # exact colors come from the runtime gtk.css generated by apply-app-themes.sh
      name = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };
    font = {
      name = "Montserrat";
      package = null;
      size = 12;
    };
    cursorTheme = {
      name = "Bibata-Modern-Ice";
      package = null;
      size = 24;
    };
    # gtk4 apps are themed by the runtime gtk.css; don't inherit the gtk3 theme
    gtk4.theme = null;
  };

  # Force the dark adw-gtk3 theme across all GTK apps (incl. Electron via
  # GTK, Qt via the gtk3 platform bridge); runtime gtk.css supplies the palette.
  home.sessionVariables.GTK_THEME = "adw-gtk3-dark";

  qt = {
    enable = true;
    platformTheme = {
      name = "gtk3";
    };
  };

  dconf = {
    enable = true;
    settings."org.gnome.desktop.interface" = {
      color-scheme = "prefer-dark";
      gtk-theme = "adw-gtk3-dark";
      cursor-theme = "Bibata-Modern-Ice";
      cursor-size = 24;
    };
  };
}
